### ISSUE TITLE
Expressing support!

### ISSUE THREAD

**Issue by jywarren** [cmisenas/potrace#4]
This is so great. I don't know if I can be of any help but I am really excited about this project; I've been hoping to make a vectorizing web-based service for turning drawings into laser-cuttable designs. Keep up the great work! also feel free to close this issue :-)

**Comment by cmisenas** [comment]
Thanks @jywarren! :)

PRs are always welcome. Currently, there are 3 bugs (see issues) and missing optimization steps (see steps in README). I've been busy lately and have not been able to get to it.
