### ISSUE TITLE
Awsome work!!

### ISSUE THREAD

**Issue by mcanthony** [cmisenas/potrace#5]
Not so much an issue.... But just wanted to say, I appreciate your efforts on this (and many of your other) projects! I envision a whole lot of image manipulation techniques that will be made possible in the browser, thanks to your hard work. I am currently focused on developing new and improved ways of editing/enhancing/restoring audio spectra by leveraging image data selection and processing techniques to allow for a more natural and visual approach to such work. Keep up the good work and let me know if there is any way I can be of assistance!

**Comment by cmisenas** [comment]
Thanks so much @mcanthony !! :smile:  I really appreciate your comments.

As always, I welcome PRs (I was bad at it when I started some of my projects but am now more open to it). For potrace, there's 3 open bugs currently that I have not had the time to get to currently. I also have other in-progress projects if you're interested as well that may use new features/feedback/ideas. 

Let me know how your project comes along. Sounds like a fun thing to implement :+1:
